### ISSUE TITLE
GitHub Reusable Workflows

### ISSUE THREAD

**Issue by antoinedelia** [antoinedelia/cloud-optimist#80]
https://docs.github.com/en/actions/sharing-automations/reusing-workflows

A reusable workflow is a special type of GitHub Actions workflow that can be called by another workflow. You define the deployment logic once in a central repository, and then all your application repositories can simply "call" this central workflow, passing in any specific parameters they need (like a service name or deployment environment).

This approach follows the **Don't Repeat Yourself (DRY)** principle, which leads to:
* Maintainability: Update the logic in one place, and all repositories that use it get the update instantly.
* Standardization: Enforce a consistent, tested deployment process across all your projects.
* Security: Centralize the management of actions and permissions. You can be confident that every project is using the approved deployment method.
* Readability: The workflows in your application repositories become much simpler and cleaner. They only need to specify _what_ to deploy, not _how_.

---

### Step 1: Create a Central Repository for Your Workflows

First, you need a dedicated repository within your GitHub organization to store your reusable workflows. This repository can be public, internal, or private.

  1. Create a new repository in your organization. A good name would be something like `reusable-workflows` or `org-actions`.
  2. Let's assume you name it `reusable-workflows`.

### Step 2: Define the Reusable Workflow File

Inside this new repository, you'll create the master workflow file that contains your AWS deployment logic.

  1. In your reusable-workflows repository, create the directory path .github/workflows/.
  2. Inside that directory, create a new YAML file. Let's name it reusable-aws-deploy.yml.

This file will contain the logic that you are currently copying everywhere. The key differences are the on: trigger and the use of inputs.

Here is a complete example of what reusable-aws-deploy.yml could look like.

```yaml
# /.github/workflows/reusable-cdk-deploy.yml

name: Reusable AWS CDK Deployment

# This workflow is triggered by a call from another workflow
on:
  workflow_call:
    # Define the inputs that calling workflows can pass
    inputs:
      python-version:
        description: 'The version of Python to set up'
        required: false
        type: string
        default: '3.13'
      node-version:
        description: 'The version of Node.js to set up'
        required: false
        type: string
        default: '22'
      working-directory:
        description: 'The directory where the CDK app is located'
        required: false
        type: string
        default: '.' # Defaults to the root directory

    # Define the secrets the calling workflow must provide
    secrets:
      AWS_ROLE_ARN:
        description: 'The AWS IAM Role to assume for deployment'
        required: true

jobs:
  deploy-cdk-stack:
    runs-on: ubuntu-latest

    # These permissions are required for aws-actions/configure-aws-credentials to use OIDC
    permissions:
      id-token: write # Required for federated credentials
      contents: read  # Required for checkout

    steps:
      # 1. Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Python using the version from the input
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      # 3. Set up Node.js using the version from the input
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      # 4. Install AWS CDK globally
      - name: Install AWS CDK
        run: npm install -g aws-cdk

      # 5. Install Python dependencies from requirements.txt
      #    This step uses the working-directory input
      - name: Set up Python dependencies
        working-directory: ${{ inputs.working-directory }}
        run: pip install -r requirements.txt

      # 6. Configure AWS credentials using OIDC Role
      #    The role ARN is passed as a secret from the calling workflow
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-1 # You could also make this an input if needed

      # 7. Deploy the CDK stack
      #    This step also uses the working-directory input
      - name: Deploy CDK Stack
        working-directory: ${{ inputs.working-directory }}
        run: cdk deploy --all --require-approval never
```

### Step 3: Allow the Reusable Workflow to be Called

If your reusable-workflows repository is private or internal, you need to configure its settings to allow other repositories in your organization to access it.

1.   Go to your reusable-workflows repository on GitHub.
2.   Click on Settings > Actions > General.
3.   Under the Access section, choose the appropriate option. To allow all repositories in your organization to use it, select "Accessible from repositories in the '&lt;your-org-name>' organization".

### Step 4: Call the Reusable Workflow from an Application Repository

Now, in each of your application repositories, you can replace the big, complex deployment workflow with a much simpler one that just calls the reusable workflow.

Create a .github/workflows/deploy.yml file in one of your app repos:

```yaml
# /my-cdk-app/.github/workflows/deploy.yml

name: Deploy CDK App to AWS

on:
  push:
    branches: [master]

jobs:
  deploy:
    # This is the call to your reusable workflow.
    # Remember to use a version tag (@v1) for stability!
    uses: MyGitHubOrg/reusable-workflows/.github/workflows/reusable-cdk-deploy.yml@v1

    # Provide the inputs required by the reusable workflow
    with:
      # Since your CDK app is in the 'infra' folder
      working-directory: 'infra' 
      # The python-version and node-version are optional since we defined defaults,
      # but you can specify them here if this project needs different versions.
      # python-version: '3.12'
      # node-version: '20'

    # Provide the secret that the reusable workflow expects.
    # This secret must be configured in this repository's settings
    # (Settings > Secrets and variables > Actions).
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
```

### Differences with GitHub Actions

* A Custom Action is a single, reusable tool or task.
* A Reusable Workflow is a complete, reusable sequence of tasks and jobs.
